import { World, Person, Task, ActivityLog, KnowledgeNote, UserStats } from '../types';

export const INITIAL_WORLDS: World[] = [
  {
    id: 'world-company',
    name: 'My Company',
    description: 'Building and growing our handcrafted wooden furniture startup and digital storefront.',
    type: 'company',
    category: 'company',
    icon: '🏢',
    emoji: '🏢',
    visualIdentity: {
      accentColor: 'indigo',
      coverGradient: 'from-indigo-600/30 via-purple-600/20 to-transparent',
      badgeText: 'Startup',
    },
    purpose: 'Build and grow my furniture business.',
    promptDescription: 'I want to build a sustainable furniture business with online sales and custom artisan orders.',
    memberCount: 4,
    peopleCount: 4,
    activeTaskCount: 4,
    activeTasksCount: 4,
    status: 'active',
    tags: ['Startup', 'Design', 'Ecommerce'],
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'world-home',
    name: 'My Home',
    description: 'Household coordination, weekly grocery planning, home renovation, and family activities.',
    type: 'home',
    category: 'home',
    icon: '🏠',
    emoji: '🏠',
    visualIdentity: {
      accentColor: 'amber',
      coverGradient: 'from-amber-600/30 via-orange-600/20 to-transparent',
      badgeText: 'Household',
    },
    purpose: 'Keep our family organized, healthy and stress-free.',
    promptDescription: 'Organize our family schedules, chore distribution, and healthy meal preparations.',
    memberCount: 3,
    peopleCount: 3,
    activeTaskCount: 2,
    activeTasksCount: 2,
    status: 'active',
    tags: ['Family', 'Meal Planning', 'Home'],
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'world-study',
    name: 'My Study World',
    description: 'Mastering modern web development, algorithms, and practical software engineering.',
    type: 'study',
    category: 'study',
    icon: '📚',
    emoji: '📚',
    visualIdentity: {
      accentColor: 'blue',
      coverGradient: 'from-blue-600/30 via-cyan-600/20 to-transparent',
      badgeText: 'Education',
    },
    purpose: 'Learn React, TypeScript and system architecture faster with intelligent study partners.',
    promptDescription: 'A quiet study environment for learning software engineering and machine learning fundamentals.',
    memberCount: 2,
    peopleCount: 2,
    activeTaskCount: 2,
    activeTasksCount: 2,
    status: 'active',
    tags: ['Learning', 'Coding', 'Computer Science'],
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'world-story',
    name: 'Elysium Chronicles',
    description: 'Collaborative fantasy tabletop universe with rich character lore, magic systems and questlines.',
    type: 'game',
    category: 'game',
    icon: '🎮',
    emoji: '🎮',
    visualIdentity: {
      accentColor: 'purple',
      coverGradient: 'from-purple-600/30 via-pink-600/20 to-transparent',
      badgeText: 'Campaign',
    },
    purpose: 'Write an immersive adventure campaign with creative characters.',
    promptDescription: 'A fantasy story world with magical kingdoms, heroic quests, and historical chronicles.',
    memberCount: 2,
    peopleCount: 2,
    activeTaskCount: 1,
    activeTasksCount: 1,
    status: 'active',
    tags: ['Storytelling', 'Fantasy', 'RPG'],
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'world-consulting',
    name: 'Apex Strategy Consulting',
    description: 'B2B market research, client deliverables, and strategic growth roadmaps.',
    type: 'business',
    category: 'business',
    icon: '💼',
    emoji: '💼',
    visualIdentity: {
      accentColor: 'emerald',
      coverGradient: 'from-emerald-600/30 via-teal-600/20 to-transparent',
      badgeText: 'Client Hub',
    },
    purpose: 'Manage client strategy consulting projects and quarterly reviews.',
    promptDescription: 'A professional business consulting space for strategy roadmaps and market evaluations.',
    memberCount: 0,
    peopleCount: 0,
    activeTaskCount: 0,
    activeTasksCount: 0,
    status: 'active',
    tags: ['Consulting', 'B2B', 'Operations'],
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_PEOPLE: Person[] = [
  // My Company
  {
    id: 'person-rahul',
    worldId: 'world-company',
    worldName: 'My Company',
    name: 'Rahul',
    role: 'CEO & Founder',
    description: 'Leads overarching company vision, investor relationships, and team alignment.',
    avatar: {
      emoji: '👨‍💼',
      gradientBg: 'from-blue-600 to-indigo-700',
      initials: 'RH',
    },
    avatarEmoji: '👨‍💼',
    avatarBg: 'from-blue-600 to-indigo-700',
    personality: {
      traits: ['Visionary', 'Pragmatic', 'Encouraging'],
      description: 'Rahul balances bold ambition with grounded operational execution. He communicates clearly and keeps team goals front and center.',
      communicationStyle: ['Professional', 'Direct', 'Friendly'],
    },
    responsibilities: [
      'Company roadmap & quarterly milestones',
      'Investor relations & fundraising',
      'High-level team coordination',
    ],
    skills: ['Strategic Planning', 'Financial Modeling', 'Public Speaking', 'Team Leadership'],
    interests: ['Sustainable Manufacturing', 'Modern Architecture', 'Angel Investing'],
    goals: [
      'Reach $500k ARR with the new handcrafted furniture line',
      'Expand regional delivery across 4 neighboring states',
    ],
    status: 'available',
    currentActivity: 'Reviewing quarterly furniture sales targets',
    tasksAssignedCount: 1,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'person-maya',
    worldId: 'world-company',
    worldName: 'My Company',
    name: 'Maya',
    role: 'Lead Developer',
    description: 'Builds and maintains customer-facing web applications, payment checkouts, and inventory tools.',
    avatar: {
      emoji: '👩‍💻',
      gradientBg: 'from-purple-600 to-pink-600',
      initials: 'MY',
    },
    avatarEmoji: '👩‍💻',
    avatarBg: 'from-purple-600 to-pink-600',
    personality: {
      traits: ['Curious', 'Analytical', 'Proactive'],
      description: 'Maya loves clean software design and problem solving. She prefers researching solutions deeply and writing modular, tested code.',
      communicationStyle: ['Analytical', 'Creative', 'Friendly'],
    },
    responsibilities: [
      'Design & build the primary ecommerce web app',
      'Stripe checkout integration & inventory sync',
      'Code quality & frontend performance optimization',
    ],
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Node.js', 'PostgreSQL', 'API Design'],
    interests: ['UI/UX Design Systems', 'Web Performance', 'Open Source'],
    goals: [
      'Launch the responsive furniture website by next month',
      'Achieve 99+ Lighthouse performance score',
    ],
    status: 'available',
    currentActivity: 'Building the company ecommerce website homepage',
    tasksAssignedCount: 2,
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'person-priya',
    worldId: 'world-company',
    worldName: 'My Company',
    name: 'Priya',
    role: 'Marketing Lead',
    description: 'Drives customer acquisition, brand storytelling, content marketing, and competitor analysis.',
    avatar: {
      emoji: '📈',
      gradientBg: 'from-amber-500 to-orange-600',
      initials: 'PR',
    },
    avatarEmoji: '📈',
    avatarBg: 'from-amber-500 to-orange-600',
    personality: {
      traits: ['Energetic', 'Data-driven', 'Creative'],
      description: 'Priya turns data insights into compelling brand narratives. She moves quickly, tests hypotheses, and iterates on marketing campaigns.',
      communicationStyle: ['Energetic', 'Creative', 'Professional'],
    },
    responsibilities: [
      'Brand identity & social media growth campaigns',
      'Competitor market research & pricing benchmarks',
      'Customer email newsletters & product announcements',
    ],
    skills: ['Content Marketing', 'SEO Optimization', 'Copywriting', 'Customer Analytics'],
    interests: ['Brand Storytelling', 'Social Media Trends', 'Interior Design'],
    goals: [
      'Grow email waitlist to 5,000 active subscribers',
      'Execute spring product launch campaign',
    ],
    status: 'busy',
    currentActivity: 'Researching competitor pricing and social media campaigns',
    tasksAssignedCount: 1,
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'person-sam',
    worldId: 'world-company',
    worldName: 'My Company',
    name: 'Sam',
    role: 'Product Designer',
    description: 'Crafts 3D furniture models, wood finish specifications, and customer unboxing experiences.',
    avatar: {
      emoji: '🎨',
      gradientBg: 'from-emerald-500 to-teal-700',
      initials: 'SM',
    },
    avatarEmoji: '🎨',
    avatarBg: 'from-emerald-500 to-teal-700',
    personality: {
      traits: ['Aesthetic-focused', 'Thoughtful', 'Calm'],
      description: 'Sam is deeply passionate about sustainable ergonomics and minimalist Scandinavian aesthetics. He is patient and pays attention to fine craftsmanship.',
      communicationStyle: ['Calm', 'Creative', 'Friendly'],
    },
    responsibilities: [
      '3D CAD product modeling & render catalogs',
      'Material & wood finish standards',
      'Eco-friendly packaging design',
    ],
    skills: ['Industrial Design', 'Blender / 3D CAD', 'Ergonomics', 'Packaging Design'],
    interests: ['Woodworking', 'Minimalist Architecture', 'Photography'],
    goals: [
      'Complete CAD prototypes for the 2026 Dining Collection',
      'Source 100% recycled packaging materials',
    ],
    status: 'available',
    currentActivity: 'Drafting 3D catalog prototypes for dining tables',
    tasksAssignedCount: 0,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // My Home
  {
    id: 'person-elena',
    worldId: 'world-home',
    worldName: 'My Home',
    name: 'Elena',
    role: 'Family Organizer',
    description: 'Plans wholesome weekly dinners, coordinates family calendars, and tracks grocery supplies.',
    avatar: {
      emoji: '👩‍🍳',
      gradientBg: 'from-rose-500 to-pink-600',
      initials: 'EL',
    },
    avatarEmoji: '👩‍🍳',
    avatarBg: 'from-rose-500 to-pink-600',
    personality: {
      traits: ['Warm', 'Caring', 'Organized'],
      description: 'Elena keeps the home warm and well-structured. She makes sure every family member is supported and well-nourished.',
      communicationStyle: ['Friendly', 'Calm', 'Professional'],
    },
    responsibilities: [
      'Weekly healthy meal planning & grocery lists',
      'Family calendar coordination & appointments',
      'Pantry & household inventory tracking',
    ],
    skills: ['Nutrition & Cooking', 'Budget Management', 'Event Planning'],
    interests: ['Mediterranean Cuisine', 'Baking', 'Family Travel'],
    goals: [
      'Establish a stress-free weekday dinner routine',
      'Organize summer family vacation itinerary',
    ],
    status: 'available',
    currentActivity: 'Creating weekly healthy dinner meal plan and grocery list',
    tasksAssignedCount: 1,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'person-marcus',
    worldId: 'world-home',
    worldName: 'My Home',
    name: 'Marcus',
    role: 'Home Maintenance Helper',
    description: 'Oversees seasonal home maintenance, garden care, and appliance warranties.',
    avatar: {
      emoji: '👨‍🔧',
      gradientBg: 'from-amber-600 to-yellow-600',
      initials: 'MC',
    },
    avatarEmoji: '👨‍🔧',
    avatarBg: 'from-amber-600 to-yellow-600',
    personality: {
      traits: ['Handy', 'Reliable', 'Practical'],
      description: 'Marcus is hands-on and practical. He prevents household issues before they start and loves fixing things efficiently.',
      communicationStyle: ['Direct', 'Calm', 'Friendly'],
    },
    responsibilities: [
      'HVAC and filter replacement schedules',
      'Garden irrigation & seasonal care',
      'Tool maintenance & DIY repair guides',
    ],
    skills: ['Home Repairs', 'Gardening', 'Safety Checks', 'Plumbing Basics'],
    interests: ['Carpentry', 'Smart Home Tech', 'Lawn Care'],
    goals: [
      'Complete spring garden soil prep and vegetable planting',
      'Inspect roof gutters and drainage before rainy season',
    ],
    status: 'available',
    currentActivity: 'Checking seasonal air filter replacement schedule',
    tasksAssignedCount: 1,
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'person-sophie',
    worldId: 'world-home',
    worldName: 'My Home',
    name: 'Sophie',
    role: 'Kids Tutor & Storyteller',
    description: 'Helps with math homework, reading comprehension, and imaginative bedtime stories.',
    avatar: {
      emoji: '👧',
      gradientBg: 'from-cyan-500 to-blue-600',
      initials: 'SP',
    },
    avatarEmoji: '👧',
    avatarBg: 'from-cyan-500 to-blue-600',
    personality: {
      traits: ['Playful', 'Patient', 'Imaginative'],
      description: 'Sophie makes learning fun and engaging. She explains tricky concepts with colorful analogies and creative storytelling.',
      communicationStyle: ['Friendly', 'Creative', 'Energetic'],
    },
    responsibilities: [
      'Elementary math practice & word problems',
      'Daily reading practice & vocabulary games',
      'Bedtime storytelling and creative drawing prompts',
    ],
    skills: ['Elementary Pedagogy', 'Interactive Storytelling', 'Children Science'],
    interests: ['Children Literature', 'Astronomy for Kids', 'Origami'],
    goals: [
      'Help kids complete 20 reading challenge books',
      'Master multiplication tables with fun games',
    ],
    status: 'available',
    currentActivity: 'Ready for evening bedtime story reading',
    tasksAssignedCount: 0,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // My Study World
  {
    id: 'person-alex',
    worldId: 'world-study',
    worldName: 'My Study World',
    name: 'Alex',
    role: 'Coding Mentor',
    description: 'Provides structured software engineering guidance, code reviews, and architecture walkthroughs.',
    avatar: {
      emoji: '🧑‍🏫',
      gradientBg: 'from-indigo-600 to-purple-700',
      initials: 'AX',
    },
    avatarEmoji: '🧑‍🏫',
    avatarBg: 'from-indigo-600 to-purple-700',
    personality: {
      traits: ['Encouraging', 'Pedagogical', 'Thorough'],
      description: 'Alex breaks down intimidating computer science concepts into clear mental models. He gives constructive feedback and celebrates progress.',
      communicationStyle: ['Professional', 'Friendly', 'Analytical'],
    },
    responsibilities: [
      'Weekly React & TypeScript coding exercises',
      'Code reviews & best practice explanations',
      'System design and data structure tutoring',
    ],
    skills: ['TypeScript', 'Fullstack Architecture', 'Data Structures', 'Testing'],
    interests: ['Compiler Theory', 'Functional Programming', 'Tech Education'],
    goals: [
      'Complete frontend architecture mastery curriculum',
      'Build 5 production-ready fullstack project portfolios',
    ],
    status: 'available',
    currentActivity: 'Preparing practice exercises for React state management',
    tasksAssignedCount: 1,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'person-leo',
    worldId: 'world-study',
    worldName: 'My Study World',
    name: 'Leo',
    role: 'Research Partner',
    description: 'Summarizes technical documentation, generates flashcards, and organizes knowledge notes.',
    avatar: {
      emoji: '🧠',
      gradientBg: 'from-violet-600 to-fuchsia-600',
      initials: 'LO',
    },
    avatarEmoji: '🧠',
    avatarBg: 'from-violet-600 to-fuchsia-600',
    personality: {
      traits: ['Inquisitive', 'Precise', 'Fast'],
      description: 'Leo loves connecting ideas across disciplines. He condenses heavy reference material into actionable study cheat-sheets.',
      communicationStyle: ['Analytical', 'Direct', 'Calm'],
    },
    responsibilities: [
      'Summarize academic papers & tech docs',
      'Spaced repetition flashcard creation',
      'Topic mind-maps and reference glossaries',
    ],
    skills: ['Technical Summarization', 'Knowledge Graphs', 'Research Synthesis'],
    interests: ['Cognitive Science', 'Information Architecture', 'Machine Learning'],
    goals: [
      'Build comprehensive knowledge graph for distributed systems',
      'Curate 200 key spaced-repetition flashcards',
    ],
    status: 'busy',
    currentActivity: 'Summarizing key takeaways from modern frontend architecture guides',
    tasksAssignedCount: 1,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_TASKS: Task[] = [
  // My Company Tasks
  {
    id: 'task-c1',
    worldId: 'world-company',
    worldName: 'My Company',
    projectName: 'Website Launch',
    title: 'Design and build the website homepage',
    description: 'Create responsive hero section, product showcase gallery, and customer review carousel.',
    assignedPersonId: 'person-maya',
    assignedPersonName: 'Maya',
    assignedPersonEmoji: '👩‍💻',
    status: 'in_progress',
    priority: 'high',
    dueDate: 'Tomorrow',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-c2',
    worldId: 'world-company',
    worldName: 'My Company',
    projectName: 'Market Research',
    title: 'Research competitor pricing & materials',
    description: 'Analyze top 5 boutique furniture brands in our region and compare wood finishes and warranties.',
    assignedPersonId: 'person-priya',
    assignedPersonName: 'Priya',
    assignedPersonEmoji: '📈',
    status: 'in_progress',
    priority: 'medium',
    dueDate: 'In 3 days',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-c3',
    worldId: 'world-company',
    worldName: 'My Company',
    projectName: 'Product Launch',
    title: 'Finalize spring dining table collection catalog',
    description: 'Select final oak and walnut wood finishes and compile dimensions for manufacture.',
    assignedPersonId: 'person-rahul',
    assignedPersonName: 'Rahul',
    assignedPersonEmoji: '👨‍💼',
    status: 'todo',
    priority: 'high',
    dueDate: 'Next week',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-c4',
    worldId: 'world-company',
    worldName: 'My Company',
    projectName: 'Website Launch',
    title: 'Set up Stripe checkout and cart preview',
    description: 'Ensure smooth one-click checkout and automated invoice generation.',
    assignedPersonId: 'person-maya',
    assignedPersonName: 'Maya',
    assignedPersonEmoji: '👩‍💻',
    status: 'todo',
    priority: 'medium',
    dueDate: 'In 5 days',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // My Home Tasks
  {
    id: 'task-h1',
    worldId: 'world-home',
    worldName: 'My Home',
    projectName: 'Weekly Meals',
    title: 'Generate grocery list for Italian pasta night',
    description: 'List fresh basil, San Marzano tomatoes, garlic, extra virgin olive oil, and parmesan.',
    assignedPersonId: 'person-elena',
    assignedPersonName: 'Elena',
    assignedPersonEmoji: '👩‍🍳',
    status: 'in_progress',
    priority: 'high',
    dueDate: 'Today at 6 PM',
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-h2',
    worldId: 'world-home',
    worldName: 'My Home',
    projectName: 'Home Maintenance',
    title: 'Schedule seasonal HVAC filter change',
    description: 'Order two 20x25x1 MERV 11 filters and schedule a calendar reminder for Saturday morning.',
    assignedPersonId: 'person-marcus',
    assignedPersonName: 'Marcus',
    assignedPersonEmoji: '👨‍🔧',
    status: 'todo',
    priority: 'low',
    dueDate: 'This Saturday',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // My Study World Tasks
  {
    id: 'task-s1',
    worldId: 'world-study',
    worldName: 'My Study World',
    projectName: 'Frontend Mastery',
    title: 'Complete 3 React custom hook exercises',
    description: 'Build useDebounce, useLocalStorage, and useIntersectionObserver with TypeScript types.',
    assignedPersonId: 'person-alex',
    assignedPersonName: 'Alex',
    assignedPersonEmoji: '🧑‍🏫',
    status: 'in_progress',
    priority: 'medium',
    dueDate: 'Tomorrow',
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-s2',
    worldId: 'world-study',
    worldName: 'My Study World',
    projectName: 'Algorithms',
    title: 'Review Dijkstra algorithm walkthrough',
    description: 'Read the summary notes on priority queue graph traversal and shortest path guarantees.',
    assignedPersonId: 'person-leo',
    assignedPersonName: 'Leo',
    assignedPersonEmoji: '🧠',
    status: 'todo',
    priority: 'low',
    dueDate: 'This weekend',
    createdAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_ACTIVITIES: ActivityLog[] = [
  {
    id: 'act-1',
    worldId: 'world-company',
    worldName: 'My Company',
    personId: 'person-maya',
    personName: 'Maya',
    personEmoji: '👩‍💻',
    action: 'Completed task',
    sentence: 'Maya finished designing the responsive website navigation bar.',
    timestamp: new Date(Date.now() - 4 * 60000).toISOString(),
    category: 'task',
  },
  {
    id: 'act-2',
    worldId: 'world-company',
    worldName: 'My Company',
    personId: 'person-priya',
    personName: 'Priya',
    personEmoji: '📈',
    action: 'Added research note',
    sentence: 'Priya summarized competitor pricing trends for solid oak dining tables.',
    timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
    category: 'note',
  },
  {
    id: 'act-3',
    worldId: 'world-home',
    worldName: 'My Home',
    personId: 'person-elena',
    personName: 'Elena',
    personEmoji: '👩‍🍳',
    action: 'Created meal plan',
    sentence: 'Elena added 5 healthy dinner recipes for next week to the family board.',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    category: 'world',
  },
  {
    id: 'act-4',
    worldId: 'world-company',
    worldName: 'My Company',
    personId: 'person-rahul',
    personName: 'Rahul',
    personEmoji: '👨‍💼',
    action: 'Created project',
    sentence: 'Rahul started a new project: "Spring 2026 Sustainable Collection Launch".',
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    category: 'task',
  },
  {
    id: 'act-5',
    worldId: 'world-study',
    worldName: 'My Study World',
    personId: 'person-alex',
    personName: 'Alex',
    personEmoji: '🧑‍🏫',
    action: 'Shared notes',
    sentence: 'Alex shared practical guidelines for organizing React component folders.',
    timestamp: new Date(Date.now() - 180 * 60000).toISOString(),
    category: 'note',
  },
];

export const INITIAL_KNOWLEDGE: KnowledgeNote[] = [
  {
    id: 'note-1',
    worldId: 'world-company',
    title: 'Brand Vision & Quality Guidelines',
    content: 'We craft sustainably-sourced, handcrafted hardwood furniture built to last generations. Every piece includes a lifetime structural warranty and timeless minimalist aesthetics.',
    category: 'guideline',
    authorName: 'Rahul (CEO)',
    tags: ['Vision', 'Brand', 'Quality'],
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'note-2',
    worldId: 'world-company',
    title: 'Website Tech Stack & Standards',
    content: 'Using React, TypeScript, and Tailwind CSS. All components must be accessible (WCAG AA), responsive from 320px up, and feature clean typography.',
    category: 'document',
    authorName: 'Maya (Lead Developer)',
    tags: ['Tech', 'Design System'],
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'note-3',
    worldId: 'world-home',
    title: 'Family Dietary Preferences & Allergies',
    content: 'Nut-free household. Prefer Mediterranean-style dinners with fresh vegetables, olive oil, and high-protein ingredients on weekdays.',
    category: 'guideline',
    authorName: 'Elena',
    tags: ['Nutrition', 'Household Rules'],
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const INITIAL_USER_STATS: UserStats = {
  totalWorlds: 5,
  totalPeople: 9,
  activeTasks: 7,
  completedTasks: 38,
};
