import { WorldTheme, ThemePreset } from '../types/experience';

export const THEME_PRESETS: Record<ThemePreset, WorldTheme> = {
  modern: {
    preset: 'modern',
    primaryColor: '#8B5CF6',
    secondaryColor: '#6366F1',
    accentColor: '#EC4899',
    backgroundColor: '#090A12',
    surfaceColor: '#121426',
    surfaceBorderColor: 'rgba(255, 255, 255, 0.08)',
    textColor: '#FFFFFF',
    mutedTextColor: '#94A3B8',
    borderRadius: 'lg',
    density: 'comfortable',
    typography: 'inter',
    shadows: 'glow',
  },
  warm: {
    preset: 'warm',
    primaryColor: '#F59E0B',
    secondaryColor: '#EA580C',
    accentColor: '#F43F5E',
    backgroundColor: '#0F0D0B',
    surfaceColor: '#1C1713',
    surfaceBorderColor: 'rgba(245, 158, 11, 0.15)',
    textColor: '#FFFBEB',
    mutedTextColor: '#D97706',
    borderRadius: 'xl',
    density: 'spacious',
    typography: 'outfit',
    shadows: 'elevated',
  },
  professional: {
    preset: 'professional',
    primaryColor: '#2563EB',
    secondaryColor: '#0284C7',
    accentColor: '#10B981',
    backgroundColor: '#0A0D14',
    surfaceColor: '#131926',
    surfaceBorderColor: 'rgba(255, 255, 255, 0.10)',
    textColor: '#F8FAFC',
    mutedTextColor: '#64748B',
    borderRadius: 'md',
    density: 'compact',
    typography: 'roboto',
    shadows: 'subtle',
  },
  luxury: {
    preset: 'luxury',
    primaryColor: '#D97706',
    secondaryColor: '#B45309',
    accentColor: '#F59E0B',
    backgroundColor: '#080706',
    surfaceColor: '#141210',
    surfaceBorderColor: 'rgba(217, 119, 6, 0.25)',
    textColor: '#FAF5EE',
    mutedTextColor: '#A8A29E',
    borderRadius: 'sm',
    density: 'spacious',
    typography: 'serif',
    shadows: 'elevated',
  },
  dark: {
    preset: 'dark',
    primaryColor: '#38BDF8',
    secondaryColor: '#818CF8',
    accentColor: '#34D399',
    backgroundColor: '#030712',
    surfaceColor: '#0F172A',
    surfaceBorderColor: 'rgba(255, 255, 255, 0.08)',
    textColor: '#F9FAFB',
    mutedTextColor: '#9CA3AF',
    borderRadius: 'lg',
    density: 'comfortable',
    typography: 'inter',
    shadows: 'glow',
  },
  playful: {
    preset: 'playful',
    primaryColor: '#EC4899',
    secondaryColor: '#8B5CF6',
    accentColor: '#F59E0B',
    backgroundColor: '#0E0717',
    surfaceColor: '#1A1028',
    surfaceBorderColor: 'rgba(236, 72, 153, 0.2)',
    textColor: '#FFFFFF',
    mutedTextColor: '#C084FC',
    borderRadius: 'full',
    density: 'comfortable',
    typography: 'outfit',
    shadows: 'glow',
  },
  minimal: {
    preset: 'minimal',
    primaryColor: '#71717A',
    secondaryColor: '#A1A1AA',
    accentColor: '#E4E4E7',
    backgroundColor: '#09090B',
    surfaceColor: '#18181B',
    surfaceBorderColor: 'rgba(255, 255, 255, 0.06)',
    textColor: '#FAFAFA',
    mutedTextColor: '#71717A',
    borderRadius: 'sm',
    density: 'compact',
    typography: 'inter',
    shadows: 'none',
  },
  elegant: {
    preset: 'elegant',
    primaryColor: '#A855F7',
    secondaryColor: '#6366F1',
    accentColor: '#F472B6',
    backgroundColor: '#0B0914',
    surfaceColor: '#161224',
    surfaceBorderColor: 'rgba(168, 85, 247, 0.15)',
    textColor: '#FAF5FF',
    mutedTextColor: '#C084FC',
    borderRadius: 'xl',
    density: 'comfortable',
    typography: 'serif',
    shadows: 'glow',
  },
  light: {
    preset: 'light',
    primaryColor: '#7C3AED',
    secondaryColor: '#4F46E5',
    accentColor: '#DB2777',
    backgroundColor: '#F8FAFC',
    surfaceColor: '#FFFFFF',
    surfaceBorderColor: 'rgba(0, 0, 0, 0.08)',
    textColor: '#0F172A',
    mutedTextColor: '#64748B',
    borderRadius: 'lg',
    density: 'comfortable',
    typography: 'inter',
    shadows: 'subtle',
  },
  custom: {
    preset: 'custom',
    primaryColor: '#8B5CF6',
    secondaryColor: '#6366F1',
    accentColor: '#EC4899',
    backgroundColor: '#090A12',
    surfaceColor: '#121426',
    surfaceBorderColor: 'rgba(255, 255, 255, 0.08)',
    textColor: '#FFFFFF',
    mutedTextColor: '#94A3B8',
    borderRadius: 'lg',
    density: 'comfortable',
    typography: 'inter',
    shadows: 'glow',
  },
};

export const themeEngine = {
  getStyleObject(theme: WorldTheme): React.CSSProperties {
    const radiusMap: Record<string, string> = {
      none: '0px',
      sm: '8px',
      md: '12px',
      lg: '16px',
      xl: '24px',
      full: '9999px',
    };

    const fontMap: Record<string, string> = {
      inter: 'Inter, -apple-system, sans-serif',
      outfit: 'Outfit, -apple-system, sans-serif',
      roboto: 'Roboto, -apple-system, sans-serif',
      serif: 'Georgia, Cambria, serif',
      mono: 'ui-monospace, monospace',
    };

    return {
      '--world-primary': theme.primaryColor,
      '--world-secondary': theme.secondaryColor,
      '--world-accent': theme.accentColor,
      '--world-bg': theme.backgroundColor,
      '--world-surface': theme.surfaceColor,
      '--world-border': theme.surfaceBorderColor,
      '--world-text': theme.textColor,
      '--world-muted': theme.mutedTextColor,
      '--world-radius': radiusMap[theme.borderRadius] || '16px',
      '--world-font': fontMap[theme.typography] || 'Inter, sans-serif',
      backgroundColor: theme.backgroundColor,
      color: theme.textColor,
      fontFamily: fontMap[theme.typography] || 'Inter, sans-serif',
    } as React.CSSProperties;
  },

  getPreset(name: ThemePreset): WorldTheme {
    return THEME_PRESETS[name] || THEME_PRESETS.modern;
  },
};
